package autocode

type ApiGroup struct {
	// Code generated by github.com/flipped-aurora/gin-vue-admin/server Begin; DO NOT EDIT.
	AutoCodeExampleApi
	TestApi
	YwAssetsApi
	YwWxUserApi
	YwInsAclApi
	YwLoginLogApi
	YwUserLastLoginApi
	// Code generated by github.com/flipped-aurora/gin-vue-admin/server End; DO NOT EDIT.
}
